[workspace]
resolver = "2"
members = [ "cli", "coordinator", "dataspine","score_tracker"]

[workspace.dependencies]
anyhow = "1.0.80"
sqlx = { version = "0.7.3", features = ["postgres", "runtime-tokio", "chrono", "uuid"] }
thiserror = "1.0.57"
uuid = "1.7.0"
