# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: proto/games.proto for package 'proto.playground'

require 'grpc'
require 'proto/games_pb'

module Proto
  module Playground
    module Games
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'proto.playground.Games'

        rpc :CancelLastScore, ::Proto::Playground::CancelLastScoreRequest, ::Proto::Playground::CancelLastScoreResponse
        rpc :CountPoints, ::Proto::Playground::CountPointsRequest, ::Proto::Playground::CountPointsResponse
        rpc :CreateGame, ::Proto::Playground::CreateGameRequest, ::Proto::Playground::Game
        rpc :GetGame, ::Proto::Playground::GetGameRequest, ::Proto::Playground::Game
        rpc :ListGames, ::Proto::Playground::ListGamesRequest, ::Proto::Playground::ListGamesResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
