# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: proto/games.proto for package 'proto.games'

require 'grpc'
require 'proto/games_pb'

module Proto
  module Games
    module Games
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'proto.games.Games'

        rpc :ListGames, ::Proto::Games::ListGamesRequest, ::Proto::Games::ListGamesResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
