# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/games.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'


descriptor_data = "\n\x11proto/games.proto\x12\x0bproto.games\x1a\x1fgoogle/protobuf/timestamp.proto\"\x12\n\x10ListGamesRequest\"5\n\x11ListGamesResponse\x12 \n\x05games\x18\x01 \x03(\x0b\x32\x11.proto.games.Game\"B\n\x04Game\x12\n\n\x02id\x18\x01 \x01(\t\x12.\n\nstart_time\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp2S\n\x05Games\x12J\n\tListGames\x12\x1d.proto.games.ListGamesRequest\x1a\x1e.proto.games.ListGamesResponseb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool

begin
  pool.add_serialized_file(descriptor_data)
rescue TypeError
  # Compatibility code: will be removed in the next major version.
  require 'google/protobuf/descriptor_pb'
  parsed = Google::Protobuf::FileDescriptorProto.decode(descriptor_data)
  parsed.clear_dependency
  serialized = parsed.class.encode(parsed)
  file = pool.add_serialized_file(serialized)
  warn "Warning: Protobuf detected an import path issue while loading generated file #{__FILE__}"
  imports = [
    ["google.protobuf.Timestamp", "google/protobuf/timestamp.proto"],
  ]
  imports.each do |type_name, expected_filename|
    import_file = pool.lookup(type_name).file_descriptor
    if import_file.name != expected_filename
      warn "- #{file.name} imports #{expected_filename}, but that import was loaded as #{import_file.name}"
    end
  end
  warn "Each proto file must use a consistent fully-qualified name."
  warn "This will become an error in the next major version."
end

module Proto
  module Games
    ListGamesRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.games.ListGamesRequest").msgclass
    ListGamesResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.games.ListGamesResponse").msgclass
    Game = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.games.Game").msgclass
  end
end
