# frozen_string_literal: true

source 'https://rubygems.org'

gem 'google-protobuf'
gem 'grpc'
gem 'grpc-tools'
gem 'puma', '~> 6.4'
gem 'sinatra', '~> 4.0'

group :development do
  gem 'rubocop'
  gem 'ruby-lsp'
end
